import Image from 'next/image';
import type{Metadata}from'next';
import Link from '@/components/site-link';
import {ArrowRight,ArrowUpRight,Check,PackageCheck,Ruler,SwatchBook,Truck} from 'lucide-react';
import {programs} from '@/lib/programs';

export const metadata:Metadata={title:{absolute:'Hotel Linen Sourcing for U.S. Hospitality Buyers | WJ Stay'},description:'Specification-led hotel bedding, towels and bath linen sourcing for hotels, management groups and hospitality distributors.'};

export default function Home(){return <main>
  <section className="hero v2-hero"><div className="hero-copy"><p className="eyebrow">FOR U.S. HOTELS, MANAGEMENT GROUPS & DISTRIBUTORS</p><h1>Hotel Linens,<br/>Built to<br/>Your Specs.</h1><p className="intro">Specification-led bedding and bath linen programs for hotels, management groups and hospitality distributors serving the U.S. market.</p><p className="hero-detail">Start from an existing specification, current supplier SKU, product photo or project requirement. We coordinate suitable production options, samples and quotations around the buyer’s actual needs.</p><div className="hero-actions"><Link className="button light" href="/request-a-quote">Request a Quote <ArrowUpRight size={18}/></Link><Link className="hero-link" href="/match-my-linen">Match My Current Linen <ArrowRight size={17}/></Link></div><div className="hero-foot">BEDDING + BATH · ONE SOURCING CONVERSATION</div></div><div className="hero-photo"><Image src="/images/hero-bedroom.png" alt="Hotel guest room with crisp white hospitality bedding" fill priority sizes="(max-width:800px) 100vw,58vw"/><span className="photo-caption">SPECIFY · SAMPLE · APPROVE · ORDER</span></div></section>

  <section className="buyer-value"><div className="value-heading"><p className="eyebrow">A BUYER-LED SOURCING MODEL</p><h2>Built around the buyer, not the catalog.</h2></div><div className="proof-strip" aria-label="Program capabilities">{[[Ruler,'Match existing specifications','Start with the product you already use and build from there.'],[SwatchBook,'U.S.-focused sizing','Hospitality dimensions and procurement language presented for U.S. buyers.'],[Truck,'Custom branding','Logo embroidery, labels, trims and private-label options where available.'],[PackageCheck,'Sample before bulk production','Commercial specifications can be reviewed through a physical sample before bulk commitment.']].map(([Icon,title,text])=><article key={String(title)}><Icon size={22}/><div><strong>{String(title)}</strong><span>{String(text)}</span></div></article>)}</div></section>

  <section className="section match-band"><div><p className="eyebrow">MATCH MY CURRENT LINEN</p><h2>Already have a linen program?<br/>Send us what you currently buy.</h2></div><div><p>Share a specification sheet, current invoice, supplier SKU or product photo. We can review your current specification and quote a comparable option and, where appropriate, an upgraded alternative.</p><div className="match-tags">{['Specification sheet','Current invoice','Supplier SKU','Product photo'].map(x=><span key={x}>{x}</span>)}</div><Link className="button" href="/match-my-linen">Send your current spec <ArrowUpRight size={18}/></Link></div></section>

  <section className="section program-section" id="programs"><div className="section-heading"><div><p className="eyebrow">CORE PROGRAMS</p><h2>Start with a clear<br/>commercial position.</h2><p className="section-lead">Five practical starting points make it easier to compare price level, guest experience and operational fit. Every program can be refined around your approved specification.</p></div><Link className="text-link" href="/products">View all 20 specifications <ArrowRight size={18}/></Link></div><div className="tier-guide">{[['Essential','Everyday hospitality value.','Economy and select-service properties.'],['Performance','Balanced for commercial laundering and repeat use.','Midscale hotels and multi-property operations.'],['Premium','Elevated material, hand feel and presentation.','Full-service, boutique and upscale properties.']].map(([tier,copy,fit])=><article key={tier}><span>{tier}</span><p>{copy}</p><small>Best fit: {fit}</small></article>)}</div><div className="program-grid">{programs.map((p,i)=><article className="program-card" key={p.id}><Link href={p.href} className="program-image"><Image src={p.image} alt={`${p.name} ${p.category.toLowerCase()} program`} fill sizes="(max-width:720px) 100vw, (max-width:1100px) 50vw, 33vw"/></Link><div className="program-copy"><div className="program-meta"><span>{String(i+1).padStart(2,'0')} / {p.category}</span><span>{p.id}</span></div><h3>{p.name}</h3><strong>{p.headline}</strong><p>{p.spec}</p><p className="buyer-fit">Best fit: {p.buyerFit}</p><Link className="card-link" href={p.href}>Review this program <ArrowUpRight size={17}/></Link></div></article>)}</div></section>

  <section className="section buyer-section"><div><p className="eyebrow">WHO WE SUPPORT</p><h2>Designed for buyers<br/>who need a clear answer.</h2></div><div className="buyer-grid">{['Hospitality distributors building a focused private-label range','Hotel groups planning an opening, renovation or replacement cycle','Commercial laundry and linen partners comparing construction and weight','Procurement teams that need coordinated bedding and bath specifications'].map((x,i)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div></section>

  <section className="process-dark"><div className="section"><div className="section-heading"><div><p className="eyebrow">FROM REQUIREMENT TO QUOTE</p><h2>A sample-first path<br/>to a workable program.</h2></div><p className="section-lead">No generic promise replaces a written specification. We define the commercial and technical details before production is discussed.</p></div><div className="four-steps">{[['01','Share the brief','Product mix, annual or initial quantity, destination and target position.'],['02','Align the spec','Confirm U.S. finished sizes, fiber, weave or GSM, construction and packing.'],['03','Review a sample','Evaluate fit, hand feel, workmanship and your laundry conditions.'],['04','Approve the order','Confirm price, minimum quantity, lead time, inspection and shipping terms.']].map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>

  <section className="section custom-preview"><div className="custom-photo"><Image src="/images/customization-v2.png" alt="Hospitality linen customization samples showing embroidery, fabric and packaging" fill sizes="(max-width:800px) 100vw,50vw"/></div><div><p className="eyebrow">MAKE THE PROGRAM YOURS</p><h2>Logo, label and packaging options—planned together.</h2><p>Build a consistent presentation across towels, bedding and retail-ready or bulk packing. Artwork, placement, color and construction are confirmed through a pre-production sample.</p><ul>{['Embroidery or woven branding','Custom sewn-in labels and care-label layout','Plain, stripe or jacquard fabric directions','Bulk hospitality or individually packed formats'].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><Link className="button" href="/customization">Explore customization <ArrowUpRight size={18}/></Link></div></section>

  <section className="section brand-message"><p className="eyebrow">THE GUEST EXPERIENCE</p><h2>A considered stay<br/>begins with the linen.</h2><p>Commercial requirements lead the specification. The final product should still support the comfort, presentation and consistency guests notice.</p></section>

  <section className="callout"><p className="eyebrow">READY FOR A USEFUL FIRST CONVERSATION?</p><h2>Send the sizes, quantities and<br/>destination you already know.</h2><p>We will use them to frame the specification questions for your program.</p><Link className="button light" href="/request-a-quote">Build your RFQ <ArrowUpRight size={18}/></Link></section>
  </main>}
