'use client';
import{useEffect,useState,type ChangeEvent,type SyntheticEvent}from'react';
import{products}from'@/lib/products';
import{Select,SelectTrigger,SelectValue,SelectContent,SelectItem}from'@/components/ui/select';
import{Checkbox}from'@/components/ui/checkbox';
import{ArrowUpRight,CheckCircle2,Paperclip}from'lucide-react';
import{site}from'@/lib/site';

const buyerTypes=['Independent Hotel / Motel','Hotel Management Company','Hospitality Distributor','Wholesaler','Commercial Laundry','Linen Service Company','Other'];
const categories=['Towels','Bedding','Pillowcases','Duvet Covers','Mattress Protectors','Multiple Categories','Other'];
const timings=['Immediately','Within 30 days','30–60 days','60–90 days','Planning stage'];
const yesNo=['Yes','No','Not sure'];

export function InquiryForm({contact=false,match=false}:{contact?:boolean;match?:boolean}){
 const[buyerType,setBuyerType]=useState(''),[category,setCategory]=useState(''),[timing,setTiming]=useState(''),[logo,setLogo]=useState('No'),[privateLabel,setPrivateLabel]=useState('No'),[startingSpec,setStartingSpec]=useState(''),[consent,setConsent]=useState(false),[fileName,setFileName]=useState('No file selected'),[busy,setBusy]=useState(false),[reference,setReference]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const sku=new URLSearchParams(window.location.search).get('product');if(!sku)return;const product=products.find(p=>p.sku===sku);if(product){setStartingSpec(product.sku);setCategory(product.category==='bath-linen'?'Towels':product.type==='Pillowcases'?'Pillowcases':product.type==='Duvet Covers'?'Duvet Covers':product.type==='Mattress Protectors'?'Mattress Protectors':'Bedding')}},[]);
 function onFile(e:ChangeEvent<HTMLInputElement>){setFileName(e.target.files?.[0]?.name||'No file selected')}
 async function submit(event:SyntheticEvent<HTMLFormElement>){event.preventDefault();setError('');const form=event.currentTarget;const data=new FormData(form);const name=String(data.get('name')||'').trim(),email=String(data.get('email')||'').trim(),company=String(data.get('company')||'').trim(),quantity=String(data.get('estimatedQuantity')||'').trim(),destination=String(data.get('destination')||'').trim();data.set('buyerType',buyerType);data.set('productCategory',category);data.set('targetTiming',timing);data.set('customLogo',logo);data.set('privateLabel',privateLabel);data.set('startingSpec',startingSpec);data.set('source',match?'match':contact?'contact':'rfq');data.set('items',JSON.stringify({productCategory:category,startingSpec,estimatedQuantity:quantity,targetTiming:timing,supplierReference:String(data.get('supplierReference')||''),targetUnitCost:String(data.get('targetUnitCost')||''),jobTitle:String(data.get('jobTitle')||'')}));if(!name||!email||!company||!quantity||!destination||!buyerType||!category||!timing||!consent){setError('Please complete all required fields and confirm we may respond to your inquiry.');return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Please enter a valid business email address.');return}const file=data.get('attachment');if(file instanceof File&&file.size>10*1024*1024){setError('Please keep the attachment under 10 MB.');return}setBusy(true);try{const response=await fetch('/api/inquiries',{method:'POST',body:data});const payload=await response.json()as{reference?:string;error?:string};if(!response.ok)throw new Error(payload.error||'Submission failed');setReference(payload.reference||'Received')}catch(e){setError(e instanceof Error?e.message:'Your request could not be submitted. Please try again.')}finally{setBusy(false)}}
 if(reference)return <section className="rfq-success" role="status"><CheckCircle2 size={34}/><p className="eyebrow">REQUEST RECEIVED · {reference}</p><h2>Thank you. Your request has been received.</h2><p>We will review the specification, quantity and delivery requirements before responding.</p><p>If additional information is needed, Paul Chen will follow up by email.</p><div><a href={`mailto:${site.email}`}>{site.email}</a><a href="https://www.wjstay.com">{site.website}</a></div></section>;
 return <form className="inquiry-form" onSubmit={submit} noValidate><input className="honeypot" name="website_confirm" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
 <div className="form-step"><span>01</span><h2>Contact information</h2></div><div className="form-grid"><label>Full name *<input name="name" autoComplete="name" required maxLength={120}/></label><label>Business email *<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><label>Company / property *<input name="company" autoComplete="organization" required maxLength={200}/></label><label>Job title <span className="optional">(optional)</span><input name="jobTitle" autoComplete="organization-title" maxLength={120}/></label></div>
 <div className="form-step"><span>02</span><h2>Business information</h2></div><div className="form-grid"><div className="select-label">Business type *<Select value={buyerType} onValueChange={v=>setBuyerType(v||'')}><SelectTrigger aria-label="Business type"><SelectValue>{buyerType||'Select business type'}</SelectValue></SelectTrigger><SelectContent>{buyerTypes.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><label>Rooms or approximate order volume<input name="volume" placeholder="e.g. 120 rooms" maxLength={160}/></label></div>
 <div className="form-step"><span>03</span><h2>Product and project</h2></div><div className="form-grid"><div className="select-label">Product category *<Select value={category} onValueChange={v=>setCategory(v||'')}><SelectTrigger aria-label="Product category"><SelectValue>{category||'Select product category'}</SelectValue></SelectTrigger><SelectContent>{categories.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="select-label">Starting specification <span className="optional">(optional)</span><Select value={startingSpec} onValueChange={v=>setStartingSpec(v||'')}><SelectTrigger aria-label="Starting specification"><SelectValue>{startingSpec?`${startingSpec} · ${products.find(p=>p.sku===startingSpec)?.name}`:'Select a website SKU'}</SelectValue></SelectTrigger><SelectContent>{products.map(p=><SelectItem value={p.sku} key={p.sku}>{p.sku} · {p.name}</SelectItem>)}</SelectContent></Select></div><label>Estimated quantity *<input name="estimatedQuantity" placeholder="e.g. 600 bath towels" required maxLength={160}/></label><label>Delivery ZIP / location *<input name="destination" placeholder="e.g. Austin, TX 78701" required maxLength={250}/></label><div className="select-label full">Target purchase timing *<Select value={timing} onValueChange={v=>setTiming(v||'')}><SelectTrigger aria-label="Target purchase timing"><SelectValue>{timing||'Select target timing'}</SelectValue></SelectTrigger><SelectContent>{timings.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div></div>
 <div className="form-step"><span>04</span><h2>Customization and current product</h2></div><div className="form-grid"><div className="select-label">Custom logo needed?<Select value={logo} onValueChange={v=>setLogo(v||'No')}><SelectTrigger aria-label="Custom logo needed"><SelectValue>{logo}</SelectValue></SelectTrigger><SelectContent>{yesNo.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div className="select-label">Private label needed?<Select value={privateLabel} onValueChange={v=>setPrivateLabel(v||'No')}><SelectTrigger aria-label="Private label needed"><SelectValue>{privateLabel}</SelectValue></SelectTrigger><SelectContent>{yesNo.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><label>Supplier SKU or product reference <span className="optional">(optional)</span><input name="supplierReference" maxLength={180}/></label><label>Current or target unit cost <span className="optional">(optional)</span><input name="targetUnitCost" placeholder="Currency and trade basis if known" maxLength={120}/></label><label className="full upload-label" id="upload"><Paperclip size={18}/><strong>Upload current specification, invoice or product photo</strong><input className="file-input" name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={onFile}/><span className="upload-button">Choose file</span><span className="file-name">{fileName}</span><small>PDF, JPG, PNG or WebP · up to 10 MB</small></label></div>
 <label className="message-label">Project notes <span className="optional">(optional)</span><textarea name="notes" rows={6} maxLength={5000} placeholder={match?'Dimensions, thread count, towel weight, fiber composition and whether you want a close match or upgrade…':'Products, sizes, materials, branding, sample needs, packing or other requirements…'}/></label><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Allow use of details to respond"/><span>I agree that these details and files may be used to evaluate and respond to this business inquiry.</span></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="button submit-button">{busy?'Submitting…':'Submit Quote Request'}<ArrowUpRight size={18}/></button></form>
}
