'use client';
import{useEffect,useState,type ChangeEvent,type SyntheticEvent}from'react';
import{useLocale,useTranslations}from'next-intl';
import{products}from'@/lib/products';
import{Select,SelectTrigger,SelectValue,SelectContent,SelectItem}from'@/components/ui/select';
import{Checkbox}from'@/components/ui/checkbox';
import{ArrowUpRight,CheckCircle2,Paperclip}from'lucide-react';
import{site}from'@/lib/site';
import{localizeProduct}from'@/lib/product-localization';
import type{AppLocale}from'@/i18n/routing';

const buyerTypes=[['Independent Hotel / Motel','hotel'],['Hotel Management Company','management'],['Hospitality Distributor','distributor'],['Wholesaler','wholesaler'],['Commercial Laundry','laundry'],['Linen Service Company','linenService'],['Other','other']] as const;
const categories=[['Towels','towels'],['Bedding','bedding'],['Pillowcases','pillowcases'],['Duvet Covers','duvetCovers'],['Mattress Protectors','protectors'],['Multiple Categories','multiple'],['Other','other']] as const;
const timings=[['Immediately','immediately'],['Within 30 days','days30'],['30–60 days','days60'],['60–90 days','days90'],['Planning stage','planning']] as const;
const answers=[['Yes','yes'],['No','no'],['Not sure','unsure']] as const;

export function InquiryForm({contact=false,match=false}:{contact?:boolean;match?:boolean}){
 const t=useTranslations('Form');
 const locale=useLocale();
 const localizedProducts=products.map(product=>localizeProduct(product,locale as AppLocale));
 const[buyerType,setBuyerType]=useState(''),[category,setCategory]=useState(''),[timing,setTiming]=useState(''),[logo,setLogo]=useState('No'),[privateLabel,setPrivateLabel]=useState('No'),[startingSpec,setStartingSpec]=useState(''),[consent,setConsent]=useState(false),[fileName,setFileName]=useState(t('noFile')),[busy,setBusy]=useState(false),[reference,setReference]=useState(''),[error,setError]=useState('');
 const buyerLabel=(value:string)=>{const item=buyerTypes.find(([v])=>v===value);return item?t(`buyerTypes.${item[1]}`):''};
 const categoryLabel=(value:string)=>{const item=categories.find(([v])=>v===value);return item?t(`categories.${item[1]}`):''};
 const timingLabel=(value:string)=>{const item=timings.find(([v])=>v===value);return item?t(`timings.${item[1]}`):''};
 const answerLabel=(value:string)=>{const item=answers.find(([v])=>v===value);return item?t(`answers.${item[1]}`):''};
 useEffect(()=>{const sku=new URLSearchParams(window.location.search).get('product');if(!sku)return;const product=products.find(p=>p.sku===sku);if(product){setStartingSpec(product.sku);setCategory(product.category==='bath-linen'?'Towels':product.type==='Pillowcases'?'Pillowcases':product.type==='Duvet Covers'?'Duvet Covers':product.type==='Mattress Protectors'?'Mattress Protectors':'Bedding')}},[]);
 function onFile(e:ChangeEvent<HTMLInputElement>){setFileName(e.target.files?.[0]?.name||t('noFile'))}
 async function submit(event:SyntheticEvent<HTMLFormElement>){event.preventDefault();setError('');const form=event.currentTarget;const data=new FormData(form);const name=String(data.get('name')||'').trim(),email=String(data.get('email')||'').trim(),company=String(data.get('company')||'').trim(),quantity=String(data.get('estimatedQuantity')||'').trim(),destination=String(data.get('destination')||'').trim();data.set('locale',locale);data.set('buyerType',buyerType);data.set('productCategory',category);data.set('targetTiming',timing);data.set('customLogo',logo);data.set('privateLabel',privateLabel);data.set('startingSpec',startingSpec);data.set('source',match?'match':contact?'contact':'rfq');data.set('items',JSON.stringify({productCategory:category,startingSpec,estimatedQuantity:quantity,targetTiming:timing,supplierReference:String(data.get('supplierReference')||''),targetUnitCost:String(data.get('targetUnitCost')||''),jobTitle:String(data.get('jobTitle')||'')}));if(!name||!email||!company||!quantity||!destination||!buyerType||!category||!timing||!consent){setError(t('requiredError'));return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError(t('emailError'));return}const file=data.get('attachment');if(file instanceof File&&file.size>10*1024*1024){setError(t('fileError'));return}setBusy(true);try{const response=await fetch('/api/inquiries',{method:'POST',body:data});const payload=await response.json()as{reference?:string;error?:string};if(!response.ok)throw new Error(payload.error||t('submitError'));setReference(payload.reference||'Received')}catch(e){setError(e instanceof Error?e.message:t('submitError'))}finally{setBusy(false)}}
 if(reference)return <section className="rfq-success" role="status"><CheckCircle2 size={34}/><p className="eyebrow">{t('received',{reference})}</p><h2>{t('thankYou')}</h2><p>{t('review')}</p><p>{t('followUp')}</p><div><a href={`mailto:${site.email}`}>{site.email}</a><a href="https://www.wjstay.com">{site.website}</a></div></section>;
 return <form className="inquiry-form" onSubmit={submit} noValidate><input className="honeypot" name="website_confirm" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
 <div className="form-step"><span>01</span><h2>{t('contactInfo')}</h2></div><div className="form-grid"><label>{t('fullName')} *<input name="name" autoComplete="name" required maxLength={120}/></label><label>{t('businessEmail')} *<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><label>{t('company')} *<input name="company" autoComplete="organization" required maxLength={200}/></label><label>{t('jobTitle')} <span className="optional">({t('optional')})</span><input name="jobTitle" autoComplete="organization-title" maxLength={120}/></label></div>
 <div className="form-step"><span>02</span><h2>{t('businessInfo')}</h2></div><div className="form-grid"><div className="select-label">{t('businessType')} *<Select value={buyerType} onValueChange={v=>setBuyerType(v||'')}><SelectTrigger aria-label={t('businessType')}><SelectValue>{buyerType?buyerLabel(buyerType):t('selectBusinessType')}</SelectValue></SelectTrigger><SelectContent>{buyerTypes.map(([value,key])=><SelectItem value={value} key={value}>{t(`buyerTypes.${key}`)}</SelectItem>)}</SelectContent></Select></div><label>{t('volume')}<input name="volume" placeholder={t('volumePlaceholder')} maxLength={160}/></label></div>
 <div className="form-step"><span>03</span><h2>{t('productProject')}</h2></div><div className="form-grid"><div className="select-label">{t('productCategory')} *<Select value={category} onValueChange={v=>setCategory(v||'')}><SelectTrigger aria-label={t('productCategory')}><SelectValue>{category?categoryLabel(category):t('selectProductCategory')}</SelectValue></SelectTrigger><SelectContent>{categories.map(([value,key])=><SelectItem value={value} key={value}>{t(`categories.${key}`)}</SelectItem>)}</SelectContent></Select></div><div className="select-label">{t('startingSpecification')} <span className="optional">({t('optional')})</span><Select value={startingSpec} onValueChange={v=>setStartingSpec(v||'')}><SelectTrigger aria-label={t('startingSpecification')}><SelectValue>{startingSpec?`${startingSpec} · ${localizedProducts.find(p=>p.sku===startingSpec)?.name}`:t('selectSku')}</SelectValue></SelectTrigger><SelectContent>{localizedProducts.map(p=><SelectItem value={p.sku} key={p.sku}>{p.sku} · {p.name}</SelectItem>)}</SelectContent></Select></div><label>{t('estimatedQuantity')} *<input name="estimatedQuantity" placeholder={t('quantityPlaceholder')} required maxLength={160}/></label><label>{t('deliveryLocation')} *<input name="destination" placeholder={t('locationPlaceholder')} required maxLength={250}/></label><div className="select-label full">{t('targetTiming')} *<Select value={timing} onValueChange={v=>setTiming(v||'')}><SelectTrigger aria-label={t('targetTiming')}><SelectValue>{timing?timingLabel(timing):t('selectTiming')}</SelectValue></SelectTrigger><SelectContent>{timings.map(([value,key])=><SelectItem value={value} key={value}>{t(`timings.${key}`)}</SelectItem>)}</SelectContent></Select></div></div>
 <div className="form-step"><span>04</span><h2>{t('customizationCurrent')}</h2></div><div className="form-grid"><div className="select-label">{t('customLogo')}<Select value={logo} onValueChange={v=>setLogo(v||'No')}><SelectTrigger aria-label={t('customLogo')}><SelectValue>{answerLabel(logo)}</SelectValue></SelectTrigger><SelectContent>{answers.map(([value,key])=><SelectItem value={value} key={value}>{t(`answers.${key}`)}</SelectItem>)}</SelectContent></Select></div><div className="select-label">{t('privateLabel')}<Select value={privateLabel} onValueChange={v=>setPrivateLabel(v||'No')}><SelectTrigger aria-label={t('privateLabel')}><SelectValue>{answerLabel(privateLabel)}</SelectValue></SelectTrigger><SelectContent>{answers.map(([value,key])=><SelectItem value={value} key={value}>{t(`answers.${key}`)}</SelectItem>)}</SelectContent></Select></div><label>{t('supplierReference')} <span className="optional">({t('optional')})</span><input name="supplierReference" maxLength={180}/></label><label>{t('targetCost')} <span className="optional">({t('optional')})</span><input name="targetUnitCost" placeholder={t('costPlaceholder')} maxLength={120}/></label><label className="full upload-label" id="upload"><Paperclip size={18}/><strong>{t('upload')}</strong><input className="file-input" name="attachment" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" onChange={onFile}/><span className="upload-button">{t('chooseFile')}</span><span className="file-name">{fileName}</span><small>{t('fileHelp')}</small></label></div>
 <label className="message-label">{t('projectNotes')} <span className="optional">({t('optional')})</span><textarea name="notes" rows={6} maxLength={5000} placeholder={match?t('matchNotesPlaceholder'):t('notesPlaceholder')}/></label><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label={t('consent')}/><span>{t('consent')}</span></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="button submit-button">{busy?t('submitting'):t('submit')}<ArrowUpRight size={18}/></button></form>
}
