import Image from'next/image';
import type{Metadata}from'next';
import{getLocale,getTranslations}from'next-intl/server';
import Link from'@/components/site-link';
import{ArrowRight,ArrowUpRight,Check,PackageCheck,Ruler,SwatchBook,Truck}from'lucide-react';
import{getPrograms}from'@/lib/programs';
import{homeContent}from'@/lib/home-content';
import{localizedMetadata}from'@/lib/metadata';
import type{AppLocale}from'@/i18n/routing';

const Lines=({text}:{text:string})=><>{text.split('\n').map((line,index)=><span key={line}>{index>0&&<br/>}{line}</span>)}</>;
export async function generateMetadata({params}:{params:Promise<{locale:AppLocale}>}):Promise<Metadata>{const{locale}=await params;const t=await getTranslations({locale,namespace:'Meta'});return localizedMetadata(locale,'/',t('homeTitle'),t('homeDescription'));}

export default async function Home(){const locale=await getLocale()as AppLocale;const c=homeContent[locale];const programs=getPrograms(locale);const icons=[Ruler,SwatchBook,Truck,PackageCheck];return <main>
  <section className="hero v2-hero"><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1><Lines text={c.title}/></h1><p className="intro">{c.intro}</p><p className="hero-detail">{c.detail}</p><div className="hero-actions"><Link className="button light" href="/request-a-quote">{c.request} <ArrowUpRight size={18}/></Link><Link className="hero-link" href="/match-my-linen">{c.match} <ArrowRight size={17}/></Link></div><div className="hero-foot">{c.heroFoot}</div></div><div className="hero-photo"><Image src="/images/hero-bedroom.png" alt={c.heroAlt} fill priority sizes="(max-width:800px) 100vw,58vw"/><span className="photo-caption">{c.caption}</span></div></section>
  <section className="buyer-value"><div className="value-heading"><p className="eyebrow">{c.buyerModel}</p><h2>{c.buyerTitle}</h2></div><div className="proof-strip" aria-label={c.buyerModel}>{c.proof.map(([title,text]:string[],i:number)=>{const Icon=icons[i];return <article key={title}><Icon size={22}/><div><strong>{title}</strong><span>{text}</span></div></article>})}</div></section>
  <section className="section match-band"><div><p className="eyebrow">{c.match}</p><h2><Lines text={c.matchTitle}/></h2></div><div><p>{c.matchText}</p><div className="match-tags">{c.tags.map((x:string)=><span key={x}>{x}</span>)}</div><Link className="button" href="/match-my-linen">{c.sendSpec} <ArrowUpRight size={18}/></Link></div></section>
  <section className="section program-section" id="programs"><div className="section-heading"><div><p className="eyebrow">{c.core}</p><h2><Lines text={c.coreTitle}/></h2><p className="section-lead">{c.coreLead}</p></div><Link className="text-link" href="/products">{c.viewAll} <ArrowRight size={18}/></Link></div><div className="tier-guide">{c.tiers.map(([tier,copy,fit]:string[])=><article key={tier}><span>{tier}</span><p>{copy}</p><small>{c.bestFit} {fit}</small></article>)}</div><div className="program-grid">{programs.map((p,i)=><article className="program-card" key={p.id}><Link href={p.href} className="program-image"><Image src={p.image} alt={`${p.name} ${locale==='es'?'programa':locale==='pt'?'programa':'program'}`} fill sizes="(max-width:720px) 100vw, (max-width:1100px) 50vw, 33vw"/></Link><div className="program-copy"><div className="program-meta"><span>{String(i+1).padStart(2,'0')} / {locale==='en'?p.category:p.category==='Bath'?(locale==='es'?'Baño':'Banho'):(locale==='es'?'Cama':'Cama')}</span><span>{p.id}</span></div><h3>{p.name}</h3><strong>{p.headline}</strong><p>{p.spec}</p><p className="buyer-fit">{c.bestFit} {p.buyerFit}</p><Link className="card-link" href={p.href}>{c.review} <ArrowUpRight size={17}/></Link></div></article>)}</div></section>
  <section className="section buyer-section"><div><p className="eyebrow">{c.support}</p><h2><Lines text={c.supportTitle}/></h2></div><div className="buyer-grid">{c.buyers.map((x:string,i:number)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div></section>
  <section className="process-dark"><div className="section"><div className="section-heading"><div><p className="eyebrow">{c.process}</p><h2><Lines text={c.processTitle}/></h2></div><p className="section-lead">{c.processLead}</p></div><div className="four-steps">{c.steps.map(([h,p]:string[],i:number)=><article key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="section custom-preview"><div className="custom-photo"><Image src="/images/customization-v2.png" alt={c.customAlt} fill sizes="(max-width:800px) 100vw,50vw"/></div><div><p className="eyebrow">{c.make}</p><h2>{c.makeTitle}</h2><p>{c.makeText}</p><ul>{c.makeItems.map((x:string)=><li key={x}><Check size={17}/>{x}</li>)}</ul><Link className="button" href="/customization">{c.explore} <ArrowUpRight size={18}/></Link></div></section>
  <section className="section brand-message"><p className="eyebrow">{c.experience}</p><h2><Lines text={c.experienceTitle}/></h2><p>{c.experienceText}</p></section>
  <section className="callout"><p className="eyebrow">{c.ready}</p><h2><Lines text={c.readyTitle}/></h2><p>{c.readyText}</p><Link className="button light" href="/request-a-quote">{c.build} <ArrowUpRight size={18}/></Link></section>
</main>}
